spring:
  application:
    name: aug-cms
  profiles:
    active: @profiles.active@
    include: mysql #用英文逗号分割如有多个
  mvc:
    pathmatch:
       matching-strategy: ant_path_matcher

server:
  port: 8080
  tomcat:
    accept-count: 800
    threads:
      max: 400
      min-spare: 200
  servlet:
    context-path: /aug-cms

#mybatis 相关配置
mybatis:
  type-aliases-package: com.hl.aug.cms.domain
  mapper-locations: classpath:mapper/**/*.xml

dubbo:
  application:
    name: aug-cms-dubbo
  protocol:
    name: dubbo
  consumer:
    check: false
